INSERT INTO exercises (name, muscle) VALUES ('Smith Machine Bench Press', 'Chest');
INSERT INTO exercises (name, muscle) VALUES ('Dumbbell Flyes', 'Chest');
INSERT INTO exercises (name, muscle) VALUES ('Incline Dumbbell Press', 'Chest');
INSERT INTO exercises (name, muscle) VALUES ('Smith Machine Incline Bench Press', 'Chest');
INSERT INTO exercises (name, muscle) VALUES ('Push-Ups', 'Chest');
INSERT INTO exercises (name, muscle) VALUES ('Chest Dips', 'Chest');
INSERT INTO exercises (name, muscle) VALUES ('Pec Deck Flies', 'Chest');
INSERT INTO exercises (name, muscle) VALUES ('Decline Barbell Bench Press', 'Chest');
INSERT INTO exercises (name, muscle) VALUES ('Barbell Squats', 'Quads');
INSERT INTO exercises (name, muscle) VALUES ('Leg Press', 'Quads');
INSERT INTO exercises (name, muscle) VALUES ('Lunges', 'Quads');
INSERT INTO exercises (name, muscle) VALUES ('Leg Extensions', 'Quads');
INSERT INTO exercises (name, muscle) VALUES ('Bulgarian Split Squats', 'Quads');
INSERT INTO exercises (name, muscle) VALUES ('Goblet Squats', 'Quads');
INSERT INTO exercises (name, muscle) VALUES ('Sissy Squats', 'Quads');
INSERT INTO exercises (name, muscle) VALUES ('Smith Machine Squats', 'Quads');
INSERT INTO exercises (name, muscle) VALUES ('Hack Squats', 'Quads');
INSERT INTO exercises (name, muscle) VALUES ('Pendulum Squats', 'Quads');
INSERT INTO exercises (name, muscle) VALUES ('Pull-Ups', 'Lats');
INSERT INTO exercises (name, muscle) VALUES ('Lat Pulldown', 'Lats');
INSERT INTO exercises (name, muscle) VALUES ('Seated Cable Rows', 'Lats');
INSERT INTO exercises (name, muscle) VALUES ('Single-Arm Dumbbell Rows', 'Lats');
INSERT INTO exercises (name, muscle) VALUES ('Inverted Rows', 'Lats');
INSERT INTO exercises (name, muscle) VALUES ('Straight-Arm Pulldown', 'Lats');
INSERT INTO exercises (name, muscle) VALUES ('Chest-Supported Rows', 'Lats');
INSERT INTO exercises (name, muscle) VALUES ('Deadlifts', 'Back');
INSERT INTO exercises (name, muscle) VALUES ('Good Mornings', 'Back');
INSERT INTO exercises (name, muscle) VALUES ('Face Pulls', 'Back');
INSERT INTO exercises (name, muscle) VALUES ('Cable Rows', 'Back');
INSERT INTO exercises (name, muscle) VALUES ('T-Bar Rows', 'Back');
INSERT INTO exercises (name, muscle) VALUES ('Barbell Rows', 'Back');
INSERT INTO exercises (name, muscle) VALUES ('Chest-Supported Rows', 'Back');
INSERT INTO exercises (name, muscle) VALUES ('Bridges', 'Back');
INSERT INTO exercises (name, muscle) VALUES ('Overhead Barbell Press', 'Shoulders');
INSERT INTO exercises (name, muscle) VALUES ('Dumbbell Lateral Raises', 'Shoulders');
INSERT INTO exercises (name, muscle) VALUES ('Front Raises', 'Shoulders');
INSERT INTO exercises (name, muscle) VALUES ('Arnold Press', 'Shoulders');
INSERT INTO exercises (name, muscle) VALUES ('Upright Rows', 'Shoulders');
INSERT INTO exercises (name, muscle) VALUES ('Reverse Pec Deck Flyes', 'Shoulders');
INSERT INTO exercises (name, muscle) VALUES ('Cable Lateral Raises', 'Shoulders');
INSERT INTO exercises (name, muscle) VALUES ('Barbell Curls', 'Biceps');
INSERT INTO exercises (name, muscle) VALUES ('Dumbbell Hammer Curls', 'Biceps');
INSERT INTO exercises (name, muscle) VALUES ('Preacher Curls', 'Biceps');
INSERT INTO exercises (name, muscle) VALUES ('Cable Curls', 'Biceps');
INSERT INTO exercises (name, muscle) VALUES ('Chin-Ups', 'Biceps');
INSERT INTO exercises (name, muscle) VALUES ('EZ-Bar Curls', 'Biceps');
INSERT INTO exercises (name, muscle) VALUES ('Incline Dumbbell Curls', 'Biceps');
INSERT INTO exercises (name, muscle) VALUES ('Zottman Curls', 'Biceps');
INSERT INTO exercises (name, muscle) VALUES ('Spider Curls', 'Biceps');
INSERT INTO exercises (name, muscle) VALUES ('Tricep Dips', 'Triceps');
INSERT INTO exercises (name, muscle) VALUES ('Skull Crushers', 'Triceps');
INSERT INTO exercises (name, muscle) VALUES ('Tricep Pushdowns', 'Triceps');
INSERT INTO exercises (name, muscle) VALUES ('Overhead Tricep Extensions', 'Triceps');
INSERT INTO exercises (name, muscle) VALUES ('Cable Overhead Tricep Extensions', 'Triceps');
INSERT INTO exercises (name, muscle) VALUES ('Kickbacks', 'Triceps');
INSERT INTO exercises (name, muscle) VALUES ('Bench Dips', 'Triceps');
INSERT INTO exercises (name, muscle) VALUES ('JM Press', 'Triceps');
INSERT INTO exercises (name, muscle) VALUES ('Standing Calf Raises', 'Calves');
INSERT INTO exercises (name, muscle) VALUES ('Seated Calf Raises', 'Calves');
INSERT INTO exercises (name, muscle) VALUES ('Donkey Calf Raises', 'Calves');
INSERT INTO exercises (name, muscle) VALUES ('Calf Press on Leg Press Machine', 'Calves');
INSERT INTO exercises (name, muscle) VALUES ('Single-Leg Calf Raises', 'Calves');
INSERT INTO exercises (name, muscle) VALUES ('Plank', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Crunches', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Leg Raises', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Bicycle Crunches', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Russian Twists', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Mountain Climbers', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Hanging Leg Raises', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Sit-Ups', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('V-Ups', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Flutter Kicks', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Machine Crunches', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Cable Crunches', 'Abs');
INSERT INTO exercises (name, muscle) VALUES ('Romanian Deadlifts', 'Hamstrings');
INSERT INTO exercises (name, muscle) VALUES ('Leg Curls', 'Hamstrings');
INSERT INTO exercises (name, muscle) VALUES ('Glute-Ham Raises', 'Hamstrings');
INSERT INTO exercises (name, muscle) VALUES ('Good Mornings', 'Hamstrings');
INSERT INTO exercises (name, muscle) VALUES ('Single-Leg Deadlifts', 'Hamstrings');
INSERT INTO exercises (name, muscle) VALUES ('Straight-Leg Deadlifts', 'Hamstrings');
